data:extend(
{
  --- Nauvis
  {
    type = "fluid",
    name = "water",
    subgroup = "fluid",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "2kJ",
    base_color = {0, 0.34, 0.6},
    flow_color = {0.7, 0.7, 0.7},
    icon = "__base__/graphics/icons/fluid/water.png",
    order = "a[fluid]-a[water]"
  },
  {
    type = "fluid",
    name = "steam",
    subgroup = "fluid",
    default_temperature = 15,
    max_temperature = 5000,
    heat_capacity = "0.2kJ",
    icon = "__base__/graphics/icons/fluid/steam.png",
    base_color = {0.5, 0.5, 0.5},
    flow_color = {1.0, 1.0, 1.0},
    order = "a[fluid]-b[steam]",
    gas_temperature = 15,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "brine",
    icon = "__outer_moons__/graphics/icons/fluid/brine.png",
    subgroup = "fluid",
    order = "a[fluid]-c[brine]",
    default_temperature = 25,
	gas_temperature = 100,
    heat_capacity = "0.1kJ",
    base_color = {0.52, 0.58, 0.69},
    flow_color = {0.62, 0.68, 0.79},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "red-mud",
    icon = "__outer_moons__/graphics/icons/fluid/red-mud.png",
    subgroup = "fluid",
    order = "a[fluid]-d[red-mud]",
    default_temperature = 25,
	gas_temperature = 100,
    heat_capacity = "0.1kJ",
    base_color = {0.52, 0.58, 0.69},
    flow_color = {0.62, 0.68, 0.79},
    auto_barrel = false
  },  
  {
    type = "fluid",
    name = "hydrogen",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/hydrogen-atom.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    order = "a[fluid]-e[hydrogen]",
    gas_temperature = -252,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "oxygen",
    icon = "__outer_moons__/graphics/icons/fluid/oxygen.png",
    subgroup = "fluid",
    order = "a[fluid]-g[oxygen]",
    default_temperature = 25,
	gas_temperature = -180,
    heat_capacity = "0.01kJ",
    base_color = {0.62, 0.11, 0.08},
    flow_color = {0.67, 0.16, 0.13},
    auto_barrel = false
  },  
  {
    type = "fluid",
    name = "hydrogen-peroxide",
    icon = "__outer_moons__/graphics/icons/fluid/hydrogen-peroxide.png",
    subgroup = "fluid",
    order = "a[fluid]-h[hydrogen-peroxide]",
    default_temperature = 25,
	gas_temperature = 150,
    heat_capacity = "0.01kJ",
    base_color = {0.52, 0.01, 0.03},
    flow_color = {0.57, 0.06, 0.03},
    auto_barrel = false
  },  
  --- Crude
  {
    type = "fluid",
    name = "crude-oil",
    subgroup = "oil-fluid",
    default_temperature = 25,
    base_color = {0, 0, 0},
    flow_color = {0.5, 0.5, 0.5},
    icon = "__base__/graphics/icons/fluid/crude-oil.png",
    order = "b[oil]-a[crude-oil]"
  },  
  {
    type = "fluid",
    name = "petroleum-gas",
    subgroup = "oil-fluid",
    default_temperature = 25,
    gas_temperature = -42,
    base_color = {0.3, 0.1, 0.3},
    flow_color = {0.8, 0.8, 0.8},
    icon = "__base__/graphics/icons/fluid/petroleum-gas.png",
    order = "b[oil]-b[petroleum-gas]"
  },
  {
    type = "fluid",
    name = "light-oil",
    subgroup = "oil-fluid",
    default_temperature = 25,
    base_color = {0.57, 0.33, 0},
    flow_color = {1, 0.73, 0.07},
    icon = "__base__/graphics/icons/fluid/light-oil.png",
    order = "b[oil]-d[light-oil]"
  },
  {
    type = "fluid",
    name = "heavy-oil",
    subgroup = "oil-fluid",
    default_temperature = 25,
    base_color = {0.5, 0.13, 0},
    flow_color = {0.85, 0.6, 0.3},
    icon = "__base__/graphics/icons/fluid/heavy-oil.png",
    order = "b[oil]-c[heavy-oil]"
  },
  {
    type = "fluid",
    name = "lubricant",
    subgroup = "oil-fluid",
    default_temperature = 25,
    base_color = {0.15, 0.32, 0.03},
    flow_color = {0.43, 0.75, 0.31},
    icon = "__base__/graphics/icons/fluid/lubricant.png",
    order = "b[oil]-e[lubricant]"
  },  
  {
    type = "fluid",
    name = "olefins",
    icon = "__outer_moons__/graphics/icons/fluid/olefins.png",
    subgroup = "oil-fluid",
    order = "b[oil]-f[olefins]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	gas_temperature = -104,
    base_color = {0.83, 0.80, 0.94},
    flow_color = {0.78, 0.75, 0.89},
  },
  {
    type = "fluid",
    name = "aromatics",
    icon = "__outer_moons__/graphics/icons/fluid/aromatics.png",
    subgroup = "oil-fluid",
    order = "b[oil]-g[aromatics]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	gas_temperature = 80,
    base_color = {0.44, 0.41, 0.53},
    flow_color = {0.49, 0.46, 0.58},
  },
  --- Natl Gas
  {
    type = "fluid",
    name = "natural-gas",
    subgroup = "natl-gas-fluid",
    default_temperature = 25,
	gas_temperature = 15,
    heat_capacity = "0.1kJ",
    base_color = {0.38, 0.32, 0.26},
    flow_color = {0.43, 0.37, 0.31},
    icon = "__outer_moons__/graphics/icons/fluid/natural-gas.png",
    order = "c[natl-gas]-a[natural-gas]"
  },
  {
    type = "fluid",
    name = "methane",
    subgroup = "natl-gas-fluid",
    default_temperature = 25,
	gas_temperature = -161,
    heat_capacity = "0.1kJ",
    base_color = {0.55, 0.55, 0.55},
    flow_color = {0.6, 0.6, 0.6},
    icon = "__outer_moons__/graphics/icons/fluid/methane.png",
    order = "c[natl-gas]-b[methane]",	
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "carbon-monoxide",
    subgroup = "natl-gas-fluid",
    default_temperature = 25,
	gas_temperature = -191,
    heat_capacity = "0.1kJ",
    base_color = {0.46, 0, 0},
    flow_color = {0.51, 0, 0},
    icon = "__outer_moons__/graphics/icons/fluid/carbon-monoxide.png",
    order = "c[natl-gas]-c[carbon-monoxide]",	
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "carbon-dioxide",
    subgroup = "natl-gas-fluid",
    default_temperature = 25,
	gas_temperature = -79,
    heat_capacity = "0.1kJ",
    base_color = {0.31, 0.04, 0.04},
    flow_color = {0.36, 0.09, 0.09},
    icon = "__outer_moons__/graphics/icons/fluid/carbon-dioxide.png",
    order = "c[natl-gas]-d[carbon-dioxide]",	
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "methanol",
    subgroup = "natl-gas-fluid",
    default_temperature = 25,
	gas_temperature = 65,
    heat_capacity = "0.1kJ",
    base_color = {0.94, 0.01, 0.01},
    flow_color = {0.99, 0.06, 0.06},
    icon = "__outer_moons__/graphics/icons/fluid/methanol.png",
    order = "c[natl-gas]-e[methanol]"
  },
  {
    type = "fluid",
    name = "formaldehyde",
    subgroup = "natl-gas-fluid",
    default_temperature = 25,
	gas_temperature = -21,
    heat_capacity = "0.1kJ",
    base_color = {0.74, 0.38, 0.38},
    flow_color = {0.79, 0.43, 0.43},
    icon = "__outer_moons__/graphics/icons/fluid/formaldehyde.png",
    order = "c[natl-gas]-f[formaldehyde]",	
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "phenol",
    subgroup = "natl-gas-fluid",
    default_temperature = 25,
	gas_temperature = 181,
    heat_capacity = "0.1kJ",
    base_color = {0.19, 0.06, 0.06},
    flow_color = {0.24, 0.11, 0.11},
    icon = "__outer_moons__/graphics/icons/fluid/phenol.png",
    order = "c[natl-gas]-g[phenol]",	
    auto_barrel = false
  },  
  --- Sulfur
  {
    type = "fluid",
    name = "sulfane",
    icon = "__outer_moons__/graphics/icons/fluid/sulfane.png",
    subgroup = "sulfur-fluid",
    order = "d[sulfur]-a[sulfane]",
    default_temperature = 25,
	gas_temperature = -60,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.76, 0.76, 0},
    flow_color = {0.66, 0.66, 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "sulfur-dioxide",
    icon = "__outer_moons__/graphics/icons/fluid/sulfur-dioxide.png",
    subgroup = "sulfur-fluid",
    order = "d[sulfur]-b[sulfur-dioxide]",
    default_temperature = 25,
	gas_temperature = -10,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.81, 0.6, 0.28},
    flow_color = {0.86, 0.65, 0.33},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "sulfuric-acid",
    subgroup = "sulfur-fluid",
    default_temperature = 25,
    base_color = {0.75, 0.65, 0.1},
    flow_color = {0.7, 1, 0.1},
    icon = "__base__/graphics/icons/fluid/sulfuric-acid.png",
    order = "d[sulfur]-c[sulfuric-acid]"
  },
  --- Nitrogen
  {
    type = "fluid",
    name = "nitrogen",
    icon = "__outer_moons__/graphics/icons/fluid/nitrogen.png",
    subgroup = "nitrogen-fluid",
    order = "e[nitrogen]-a[nitrogen]",
    default_temperature = 25,
	gas_temperature = -195,
    heat_capacity = "0.1kJ",
    base_color = {0.11, 0.21, 0.74},
    flow_color = {0.16, 0.26, 0.79},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "ammonia",
    subgroup = "nitrogen-fluid",
    icon = "__outer_moons__/graphics/icons/fluid/ammonia.png",
    order = "e[nitrogen]-b[ammonia]",
    default_temperature = 25,
    gas_temperature = -33,
    heat_capacity = "0.1kJ",
    base_color = {0, 0, 0.6},
    flow_color = {0, 0, 0.7},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "nitric-acid",
    subgroup = "nitrogen-fluid",
    icon = "__outer_moons__/graphics/icons/fluid/nitric-acid.png",
    order = "e[nitrogen]-c[nitric-acid]",
    default_temperature = 25,
    gas_temperature = 83,
    heat_capacity = "0.1kJ",
    base_color = {0.38, 0.21, 0.74},
    flow_color = {0.43, 0.26, 0.79},
    --auto_barrel = false
  },
  --- Chlorine
  {
    type = "fluid",
    name = "chlorine",
    icon = "__outer_moons__/graphics/icons/fluid/chlorine.png",
    subgroup = "chlorine-fluid",
    order = "f[chlorine]-a[chlorine]",
    default_temperature = 25,
	gas_temperature = -34,
    heat_capacity = "0.1kJ",
    base_color = {0, 0.79, 0},
    flow_color = {0, 0.84, 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "hydrochloric-acid",
    icon = "__outer_moons__/graphics/icons/fluid/hydrochloric-acid.png",
    subgroup = "chlorine-fluid",
    order = "f[chlorine]-b[hydrochloric-acid]",
    default_temperature = 25,
	gas_temperature = -85,
    heat_capacity = "0.1kJ",
    base_color = {0.36, 0.62, 0.36},
    flow_color = {0.46, 0.72, 0.46},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "vinyl-chloride",
    icon = "__outer_moons__/graphics/icons/fluid/vinyl-chloride.png",
    subgroup = "chlorine-fluid",
    order = "f[chlorine]-c[vinyl-chloride]",
    default_temperature = 25,
	gas_temperature = -13,
    heat_capacity = "0.1kJ",
    base_color = {0.24, 0.38, 0.24},
    flow_color = {0.29, 0.43, 0.29},
    auto_barrel = false
  },
  --- Selene/Noble Gases
   {
    type = "fluid",
    name = "helium",
    icon = "__pbnuclear__/graphics/icons/fluid/helium-atom-large.png",
    subgroup = "selene-fluid",
    order = "g[selene]-c[helium]",
    default_temperature = 25,
	gas_temperature = -269,
    heat_capacity = "0.1kJ",
    base_color = {0.5, 0.23, 0.32},
    flow_color = {0.5, 0.23, 0.32},
    auto_barrel = false
  },
  --- Vulcanus
  {
    type = "fluid",
    name = "volcanic-gas",
    icon = "__outer_moons__/graphics/icons/fluid/volcanic-gas.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-a[volcanic-gas]",
    default_temperature = 1000,
    gas_temperature = 700,
    max_temperature = 2000,
    heat_capacity = "0.01kJ",
    base_color = {0.8, 0.64, 0.33},
    flow_color = {0.85, 0.69, 38},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "lava",
    icon = "__space-age__/graphics/icons/fluid/lava.png",
    subgroup = "lava-fluid",
    order = "h[vulcanus]-b[lava]",
    default_temperature = 1500,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {1, 0.4, 0.1},
    flow_color = {0.3, 0.1, 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-iron",
    icon = "__space-age__/graphics/icons/fluid/molten-iron.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-c[molten-iron]",
    default_temperature = 1500,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.2, 0.68, 0.93},
    flow_color = {0.2, 0.68, 0.93},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-copper",
    icon = "__space-age__/graphics/icons/fluid/molten-copper.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-d[molten-copper]",
    default_temperature = 1100,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.93, 0.68, 0.2},
    flow_color = {0.93, 0.68, 0.2},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-lead",
    icon = "__outer_moons__/graphics/icons/fluid/molten-lead.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-e[molten-lead]",
    default_temperature = 330,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.53, 0.43, 0.35},
    flow_color = {0.53, 0.43, 0.35},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-nickel",
    icon = "__outer_moons__/graphics/icons/fluid/molten-nickel.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-f[molten-nickel]",
    default_temperature = 1455,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.30, 0.46, 0.38},
    flow_color = {0.30, 0.46, 0.38},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-aluminum",
    icon = "__outer_moons__/graphics/icons/fluid/molten-aluminum.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-g[molten-aluminum]",
    default_temperature = 660,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.62, 0.29, 0.32},
    flow_color = {0.62, 0.29, 0.32},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-silicon",
    icon = "__outer_moons__/graphics/icons/fluid/molten-silicon.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-h[molten-silicon]",
    default_temperature = 1415,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.4, 0.4, 0.6},
    flow_color = {0.4, 0.4, 0.6},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-titanium",
    icon = "__outer_moons__/graphics/icons/fluid/molten-titanium.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-i[molten-titanium]",
    default_temperature = 1725,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.64, 0.46, 0.58},
    flow_color = {0.64, 0.46, 0.58},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-magnesium",
    icon = "__outer_moons__/graphics/icons/fluid/molten-magnesium.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-j[molten-magnesium]",
    default_temperature = 650,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.93, 0.93, 0.93},
    flow_color = {0.93, 0.93, 0.93},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-tungsten",
    icon = "__outer_moons__/graphics/icons/fluid/molten-tungsten.png",
    subgroup = "vulcanus-fluid",
    order = "h[vulcanus]-k[molten-tungsten]",
    default_temperature = 3420,
    max_temperature = 4000,
    heat_capacity = "0.01kJ",
    base_color = {0.37, 0.26, 0.46},
    flow_color = {0.37, 0.26, 0.46},
    auto_barrel = false
  },
  --- Gleba
  {
    type = "fluid",
    name = "slipgoo",
    icon = "__outer_moons__/graphics/icons/fluid/slipgoo.png",
    subgroup = "gleba-fluid",
    order = "i[gleba]-a[slipgoo]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.19, 0.69, 0.45},
    flow_color = {0.24, 0.74, 0.5},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "mawslush",
    icon = "__outer_moons__/graphics/icons/fluid/mawslush.png",
    subgroup = "gleba-fluid",
    order = "i[gleba]-b[mawslush]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.45, 0.08, 0.11},
    flow_color = {0.5, 0.13, 0.16},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "bioslurry",
    icon = "__outer_moons__/graphics/icons/fluid/bioslurry.png",
    subgroup = "gleba-fluid",
    order = "i[gleba]-c[bioslurry]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.74, 0.19, 0.44},
    flow_color = {0.79, 0.24, 0.49},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "ethanol",
    icon = "__outer_moons__/graphics/icons/fluid/ethanol.png",
    subgroup = "gleba-fluid",
    order = "i[gleba]-d[ethanol]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.49, 0.71, 0.62},
    flow_color = {0.54, 0.76, 0.67},
    --auto_barrel = false
  },
  {
    type = "fluid",
    name = "glycerol",
    icon = "__outer_moons__/graphics/icons/fluid/glycerol.png",
    subgroup = "gleba-fluid",
    order = "i[gleba]-e[glycerol]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.87, 0.55, 0.55},
    flow_color = {0.82, 0.6, 0.6},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "nitroglycerin",
    icon = "__outer_moons__/graphics/icons/fluid/nitroglycerin.png",
    subgroup = "gleba-fluid",
    order = "i[gleba]-f[nitroglycerin]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.55, 0.46, 0.62},
    flow_color = {0.6, 0.51, 0.67},
    auto_barrel = false
  },
  --- Fulgora  
  {
    type = "fluid",
    name = "sludge",
    icon = "__outer_moons__/graphics/icons/fluid/fulgoran-sludge.png",
    subgroup = "fulgora-fluid",
    order = "j[fulgora]-a[sludge]",
    default_temperature = 5,
    --max_temperature = 2000,
    heat_capacity = "0.1kJ",
    base_color = {0.24, 0.16, 0.16},
    flow_color = {0.12, 0.08, 0.08},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "holmium-solution",
    icon = "__space-age__/graphics/icons/fluid/holmium-solution.png",
    subgroup = "fulgora-fluid",
    order = "j[fulgora]-b[holmium-solution]",
    default_temperature = 15,
    max_temperature = 2000,
    heat_capacity = "0.01kJ",
    base_color = {0.53, 0.1, 53},
    flow_color = {0.93, 0.68, 0.73},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "electrolyte",
    icon = "__space-age__/graphics/icons/fluid/electrolyte.png",
    subgroup = "fulgora-fluid",
    order = "j[fulgora]-c[electrolyte]",
    default_temperature = 15,
    max_temperature = 500,
    heat_capacity = "0.01kJ",
    base_color = {0.8, 0.01, 0.2},
    flow_color = {0.99, 0.01, 0.3},
    auto_barrel = false
  },
  --- Mefitis  
  {
    type = "fluid",
    name = "arsenic-solution",
    subgroup = "mefitis-fluid",
    default_temperature = -25,
	gas_temperature = 150,
    heat_capacity = "0.01kJ",
    base_color = {0.6, 0, 0.11},
    flow_color = {0.65, 0, 0.16},
    icon = "__outer_moons__/graphics/icons/fluid/arsenic-solution.png",
    order = "k[mefitis]-a[arsenic-solution]",	
    auto_barrel = false
  },
  --- Aquilo
  {
    type = "fluid",
    name = "ammoniacal-solution",
    icon = "__space-age__/graphics/icons/fluid/ammoniacal-solution.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-a[ammoniacal-solution]",
    default_temperature = -50,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0, 0.15, 0.4},
    flow_color = {0, 0.35, 0.7},
    auto_barrel = false
  },  
  {
    type = "fluid",
    name = "lithium-brine",
    icon = "__space-age__/graphics/icons/fluid/lithium-brine.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-b[lithium-brine]",
    default_temperature = 15,
    heat_capacity = "0.1kJ",
    base_color = {0.8, 0.85, .8},
    flow_color = {0.6, 0.65, 0.6},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "fluorine",
    icon = "__outer_moons__/graphics/icons/fluid/fluorine.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-c[fluorine]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
    base_color = {0.0, 0.3, 0.15},
    flow_color = {0.1, 0.7, 0.4},
    gas_temperature = 15,
    auto_barrel = false
  },  
  {
    type = "fluid",
    name = "fluoroketone-hot",
    icon = "__space-age__/graphics/icons/fluid/fluoroketone-hot.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-d[fluoroketone-hot]",
    default_temperature = 180,
    heat_capacity = "1kJ",
    base_color = {0.3, 0.3, 0.10},
    flow_color = {0.4, 0.7, 0.35},
  },
  {
    type = "fluid",
    name = "fluoroketone-cold",
    icon = "__space-age__/graphics/icons/fluid/fluoroketone-cold.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-e[fluoroketone-cold]",
    default_temperature = -150,
    max_temperature = 180,
    heat_capacity = "1kJ",
    base_color = {0.0, 0.3, 0.15},
    flow_color = {0.1, 0.7, 0.4},
  },
  --- Aiolos
  {
    type = "fluid",
    name = "aliphatic-solution",
    subgroup = "aiolos-fluid",
    default_temperature = -25,
	gas_temperature = 150,
    heat_capacity = "0.01kJ",
    base_color = {0.2, 0.2, 0.2},
    flow_color = {0.25, 0.25, 0.25},
    icon = "__outer_moons__/graphics/icons/fluid/aliphatic-solution.png",
    order = "m[aiolos]-a[aliphatic-solution]",	
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "phosphine",
    icon = "__outer_moons__/graphics/icons/fluid/phosphine.png",
    subgroup = "aiolos-fluid",
    order = "m[aiolos]-b[phosphine]",
    default_temperature = 25,
    gas_temperature = -88,
    heat_capacity = "0.01kJ",
    base_color = {0.89, 0.45, 0},
    flow_color = {0.89, 0.45, 0},
    auto_barrel = false
  },  
  {
    type = "fluid",
    name = "phosphoric-acid",
    icon = "__outer_moons__/graphics/icons/fluid/phosphoric-acid.png",
    subgroup = "aiolos-fluid",
    order = "m[aiolos]-c[phosphoric-acid]",
    default_temperature = 25,
    gas_temperature = 42,
    heat_capacity = "0.01kJ",
    base_color = {0.62, 0.31, 0},
    flow_color = {0.62, 0.31, 0},
    --auto_barrel = false
  },  
  --- Feronia
  {
    type = "fluid",
    name = "iodic-solution",
    subgroup = "feronia-fluid",
    default_temperature = 25,
	gas_temperature = 150,
    heat_capacity = "0.01kJ",
    base_color = {0.34, 0, 0.4},
    flow_color = {0.39, 0, 0.45},
    icon = "__outer_moons__/graphics/icons/fluid/iodic-solution.png",
    order = "n[feronia]-a[iodic-solution]",	
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "iodine",
    icon = "__outer_moons__/graphics/icons/fluid/iodine.png",
    subgroup = "feronia-fluid",
    order = "n[feronia]-b[iodine]",
    default_temperature = 25,
    gas_temperature = 184,
    heat_capacity = "0.01kJ",
    base_color = {0.4, 0.08, 0.62},
    flow_color = {0.4, 0.08, 0.62},
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "hydroiodic-acid",
    icon = "__outer_moons__/graphics/icons/fluid/hydroiodic-acid.png",
    subgroup = "feronia-fluid",
    order = "n[feronia]-c[hydroiodic-acid]",
    default_temperature = 25,
    gas_temperature = -35,
    heat_capacity = "0.01kJ",
    base_color = {0.5, 0.37, 0.59},
    flow_color = {0.5, 0.37, 0.59},
   -- auto_barrel = false
  },  
  --- Space
  {
    type = "fluid",
    name = "thruster-fuel",
    icon = "__space-age__/graphics/icons/fluid/thruster-fuel.png",
    subgroup = "space-fluid",
    order = "z[space]-a[thruster-fuel]",
    default_temperature = 25,
    fuel_value = "50kJ",
    base_color = {0.53, 0.1, 0},
    flow_color = {0.93, 0.68, 0.2},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "thruster-oxidizer",
    icon = "__space-age__/graphics/icons/fluid/thruster-oxidizer.png",
    subgroup = "space-fluid",
    order = "z[space]-b[thruster-oxidizer]",
    default_temperature = 25,
    fuel_value = "50kJ",
    base_color = {0.0, 0.1, 0.53},
    flow_color = {0.2, 0.68, 0.93},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "fusion-plasma",
    icon = "__space-age__/graphics/icons/fluid/fusion-plasma.png",
    subgroup = "space-fluid",
    order = "z[space]-g[fusion-plasma]",
    default_temperature = 1000000,
    max_temperature = 10000000,
    heat_capacity = "25J",
    base_color = {0.0, 0.1, 0.53},
    flow_color = {0.2, 0.68, 0.93},
    auto_barrel = false
  },
})

data:extend(
{
  {
    type = "fluid",
    name = "deuterium",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/deuterium-atom-large.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    order = "a[fluid]-f[deuterium]",
    gas_temperature = -249,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "tritium",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/tritium-atom-large.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    order = "a[fluid]-f[tritium]",
    gas_temperature = -248,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "uranium-hexafluoride",
    default_temperature = 25,
    base_color = {0.2, 0.4, 0.05},
    flow_color = {0.5, 0.9, 0.4},
    icon = "__pbnuclear__/graphics/icons/fluid/uranium-hexafluoride.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-g[UF6]",
  },
  {
    type = "fluid",
    name = "uranium-235-hexafluoride",
    default_temperature = 25,
    base_color = {0.3, 0.5, 0.07},
    flow_color = {0.55, 0.95, 0.45},
    icon = "__pbnuclear__/graphics/icons/fluid/uranium-235-hexafluoride.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-h[U235F6]",
  },
  {
    type = "fluid",
    name = "uranium-238-hexafluoride", --depleted hexafluoride
    default_temperature = 25,
    base_color = {0.15, 0.32, 0.03},
    flow_color = {0.43, 0.75, 0.31},
    icon = "__pbnuclear__/graphics/icons/fluid/uranium-238-hexafluoride.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-i[U238F6]",
  },
  {
    type = "fluid",
    name = "hydrofluoric-acid",
    icon = "__pbnuclear__/graphics/icons/fluid/hydrofluoric-acid.png",
    subgroup = "aquilo-fluid",
    order = "l[aquilo]-c[hydrofluoric-acid]",
    default_temperature = 25,
    gas_temperature = -35,
    heat_capacity = "0.01kJ",
    base_color = {0.5, 0.37, 0.59},
    flow_color = {0.5, 0.37, 0.59},
   -- auto_barrel = false
  },  
   -- Selene/Noble Gases
  {
    type = "fluid",
    name = "noble-gas-mixture",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/noble-gas-mixture.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    subgroup = "selene-fluid",
    order = "g[selene]-a[noble-gas-mixture]",
    gas_temperature = -246,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "helium-3",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/helion-fixed-atom-large.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    subgroup = "selene-fluid",
    order = "g[selene]-b[helion]",
    gas_temperature = -270,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "neon",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/neon-pubchem-element10.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    subgroup = "selene-fluid",
    order = "g[selene]-d[neon]",
    gas_temperature = -246,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "argon",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/argon-pubchem-element18.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    subgroup = "selene-fluid",
    order = "g[selene]-e[argon]",
    gas_temperature = -186,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "krypton",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/krypton-pubchem.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    subgroup = "selene-fluid",
    order = "g[selene]-e[krypton]",
    gas_temperature = -120,
    auto_barrel = false
  }, 
  {
    type = "fluid",
    name = "xenon",
    subgroup = "fluid",
    default_temperature = 25,
    heat_capacity = "0.01kJ",
    icon = "__pbnuclear__/graphics/icons/fluid/xenon-pubchem.png",
    base_color = {0.95, 0.95, 0.95},
    flow_color = {0.9, 0.9, 0.9},
    subgroup = "selene-fluid",
    order = "g[selene]-e[xenon]",
    gas_temperature = -108,
    auto_barrel = false
  }, 
})