--data.lua

--require("prototypes.item-groups")
require("prototypes.fluid")
require("prototypes.item")
require("prototypes.recipe") 
require("prototypes.technology") 
require("prototypes.tile.tiles-gleba")
require("prototypes.tile.tiles")
require("prototypes.entity.resources")
require("prototypes.particles")
require("prototypes.entity.plants")
require("prototypes.decorative.decoratives-gleba")
--require("prototypes.entity.trees")
--require("prototypes.planet.planet")